apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-application-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-01
  template:
    metadata:
      labels:
        app: spring-01
    spec:
      containers:
        - name: spring-application-01
          image: public.ecr.aws/e4a0x4z6/testing-02
          ports:
            - name: spring-app 
              containerPort: 8080