
apiVersion: v1
kind: Service
metadata:
  name: spring-application-nodeport-service
spec:
  selector:
    app: spring-01
  type: NodePort
  ports:
    - name: http
      nodePort: 32134
      port: 8080
      targetPort: 8080