name: SSH into Remote Machine

on:
  push:
    branches:
      - main

jobs:
  ssh:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: SSH into Remote Machine
      uses: appleboy/ssh-action@master
      with:
        host: 54.221.164.28
        username: ubuntu
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          # Commands to run on the remote machine
          echo "Hello from GitHub Actions!"
